### ISSUE TITLE
binutils: ar does not load lto plugin automatically

### ISSUE THREAD

**Issue by pmer** [void-linux/void-packages#18725]
`ar` should pick up and find the lto plugin automatically—it should succeed without the user needing to invoke `gcc-ar`.

This works in Ubuntu 18.04, although I'm not sure exactly what they did to solve it yet.

### System
* xuname:  Void 5.4.17_1 x86_64-musl GenuineIntel/VM uptodate rFFF
* package:  binutils-2.33.1_1 gcc-9.2.0-3

### Expected behavior

No errors.

### Actual behavior

```
ar: a.o: plugin needed to handle lto object
/bin/ld: /usr/lib/gcc/x86_64-linux-musl/../../../../lib/Scrt1.o: in function `_start_c':
/builddir/musl-1.1.24/crt/crt1.c:18: undefined reference to `main'
collect2: error: ld returned 1 exit status
```

### Steps to reproduce the behavior

```
cat > a.c <<EOF
int main() {
    return 0;
}
EOF
cc a.c -c -o a.o -flto
ar qc a.a a.o
cc a.a
```

Note: if the the lto plugin is given to`ar`, i.e., with:

```
ar --plugin=/usr/lib/gcc/x86_64-linux-musl/9.2/liblto_plugin.so qc a.a a.o
```

or

```
gcc-ar qc a.a a.o  # This is a wrapper around ar provided by GCC that simply adds the --plugin line above for you.
```

then everything works fine.

**Comment by leahneukirchen** [comment]
This can be fixed by

```
mkdir -p /usr/lib/bfd-pluginsx
ln -sfr /usr/libexec/gcc/x86_64-linux-musl/9.2.0/liblto_plugin.so /usr/lib/bfd-plugins
```

And likewise for LLVMgold.so.

These links should be added to gcc and clang packages.

**Comment by q66** [comment]
@xtraeme so, why did we update gcc without fixing this first?
