### ISSUE TITLE
nvidia340: broken with linux5.4

### ISSUE THREAD

**Issue by Hoshpak** [void-linux/void-packages#19199]
### System

* xuname:  
  Void 5.4.17_1 i686 GenuineIntel uptodate rrDDFFF
* package:  
  nvidia340-340.108_2

### Expected behavior

The module should compile with linux5.4 since it's the last version that is officially supported and worked before.
### Actual behavior

Compilation fails with:

```
In file included from ./include/linux/efi.h:20,
                 from /var/lib/dkms/nvidia/340.108/build/nv-linux.h:173,
                 from /var/lib/dkms/nvidia/340.108/build/nv.c:13:
./include/linux/rtc.h: In function 'rtc_tv_nsec_ok':
./include/linux/rtc.h:238:22: warning: comparison of integer expressions of different signedness: 'long int' and 'long unsigned int' [-Wsign-compare]
  238 |  if (to_set->tv_nsec < TIME_SET_NSEC_FUZZ) {
      |                      ^
./include/linux/rtc.h:243:22: warning: comparison of integer expressions of different signedness: 'long int' and 'long unsigned int' [-Wsign-compare]
  243 |  if (to_set->tv_nsec > NSEC_PER_SEC - TIME_SET_NSEC_FUZZ) {
      |                      ^
/var/lib/dkms/nvidia/340.108/build/nv.c: In function 'nvidia_init_module':
/var/lib/dkms/nvidia/340.108/build/nv.c:755:88: error: macro "NV_KMEM_CACHE_CREATE_FULL_USERCOPY" requires 7 arguments, but only 3 given
  755 |     NV_KMEM_CACHE_CREATE_FULL_USERCOPY(nv_stack_t_cache, NV_STACK_CACHE_STR, nv_stack_t);
      |                                                                                        ^
In file included from /var/lib/dkms/nvidia/340.108/build/nv.c:13:
/var/lib/dkms/nvidia/340.108/build/nv-linux.h:1193: note: macro "NV_KMEM_CACHE_CREATE_FULL_USERCOPY" defined here
 1193 | #define NV_KMEM_CACHE_CREATE_FULL_USERCOPY(name, size, align, flags, useroffset, usersize, ctor) \
      | 
/var/lib/dkms/nvidia/340.108/build/nv.c:755:5: error: 'NV_KMEM_CACHE_CREATE_FULL_USERCOPY' undeclared (first use in this function)
  755 |     NV_KMEM_CACHE_CREATE_FULL_USERCOPY(nv_stack_t_cache, NV_STACK_CACHE_STR, nv_stack_t);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/nvidia/340.108/build/nv.c:755:5: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [scripts/Makefile.build:266: /var/lib/dkms/nvidia/340.108/build/nv.o] Fehler 1
make[2]: *** Es wird auf noch nicht beendete Prozesse gewartet....
make[1]: *** [Makefile:1652: /var/lib/dkms/nvidia/340.108/build] Fehler 2
make[1]: Verzeichnis „/usr/src/kernel-headers-5.4.19_1“ wird verlassen
NVIDIA: left KBUILD.
nvidia.ko failed to build!
make: *** [Makefile:197: nvidia.ko] Fehler 1
```
### Steps to reproduce the behavior

1. Install linux5.4 and linux5.4-headers
2. Install nvidia340

@jbenden   @xtraeme
