### ISSUE TITLE
Ansible get_url does not work

### ISSUE THREAD

**Issue by jhe2** [void-linux/void-packages#47483]
### Is this a new report?

Yes

### System Info

Void 6.5.11_1 x86_64 AuthenticAMD uptodate rrmFFFFFFFFFF

### Package(s) Affected

ansible-8.0.0_2

### Expected behaviour

When using the Ansible `get_url` module, the module should fetch the resource at the specified URL.

### Actual behaviour

Instead of fetching the URL, it fails with an error message: "An unknown error occurred: HTTPSConnection.__init__() got an unexpected keyword argument 'cert_file'".

The `cert_file` argument to `http.client.HTTPSConnection` was dropped in Python 3.12. The problem could possibly be caused by an outdated version of `python3-urllib`, which is used by the `get_url` module.

### Steps to reproduce

With Ansible installed, try using the `get_url` module, e.g.
```
ansible -i inventory -m get_url -a '{ "dest": "/tmp", "url": "https://duck.com/"}' localhost
```
This results in the following error:
```
localhost | FAILED! => {
    "changed": false,
    "dest": "/tmp",
    "elapsed": 0,
    "gid": 0,
    "group": "root",
    "mode": "01777",
    "msg": "An unknown error occurred: HTTPSConnection.__init__() got an unexpected keyword argument 'cert_file'",
    "owner": "root",
    "size": 320,
    "state": "directory",
    "uid": 0,
    "url": "https://duck.com/"
}
```

**Comment by classabbyamp** [comment]
@jcgruenhage looks like this is fixed in 2.16.0 (https://github.com/ansible/ansible/commit/0df794e5a4fe4597ee65b0d492fbf0d0989d5ca0)

**Comment by dataCobra** [comment]
Hey,

I created a PR with all the updates relevant for Ansible.

With this PR your issue should be resolved too. :+1:

**Comment by panticz** [comment]
After update Ansible to v8.7.0 the get_url function seams to work fine again:
```
pip install -U ansible

pip list | grep ansible
ansible                   8.7.0
ansible-core              2.15.11
```
