### PR TITLE
Fail go build when $go_import_path is not set

### PR DESCRIPTION
**Pull request by knusbaum**
Go builds fail anyway when the variable isn't set, but the reason is far from obvious.
This patch causes `build-style=go` builds to explicitly fail when the variable has not been set.

### CODE REVIEW

**Comment by Vaelatern** [comment]
I agree with @lemmi, but think that the right place is in the do_configure() function. I'd rather not mix setting env variables and logic that can cause a hard stop in xbps-src.

**Comment by knusbaum** [comment]
I'll move it into do_configure()

**Comment by knusbaum** [comment]
Just rebased. Not sure why there were conflicts.

**Comment by lemmi** [comment]
I'm fine with this, but I almost liked to see someone rebuild all or a good bunch of our go packages, just to make sure we aren't breaking anything. If no one else has any resources available, I could attempt a build probably within the next 2 days.

**Comment by knusbaum** [comment]
That's a good idea. I have some spare cycles to test as well.

**Comment by Vaelatern** [comment]
I have preliminarily confirmed that all build_style=go packages have go_import_path in the template.

**Comment by knusbaum** [comment]
I attempted to build every package with `build_style=go`. 
I managed to successfully package almost all of them.
The ones that would not build produced errors that I believe are unrelated to my change. I also tested them on master branch (without this change) and they produced the same errors.

Packages built:
```
NetAuth
NetAuth-nsscache
NetAuth-server
NetKeys
PopCorn
PopCorn-Server
TerraState
acbuild
acmetool
alertmanager
annie
antibody
archiver
arduino-cli
atlantis
bettercap
blackbox_exporter
blush
browserpass
caddy
cdetect
cfssl
cfssljson
cgrps
chroma
chronograf
codesearch
consul
containerd
crane
cri-tools
darch
dep
dht-node
direnv
dnote-cli
docker-gen
docker-machine
docker-machine-driver-kvm2
docker2aci
drive
elvish
etcd
figurine
flannel
flint
forego
frp
fs-repo-migrations
fzf
gendesk
ghq
gister
git-lfs
gitea
github-opml
gkill
glide
glock
go-bindata
go-gdm
go-ipfs
go-jira
go-md2man
go-mtpfs
goat
gobuster
gogs
gopm
goproxy
gops
gosh
gotop
gotty
govendor
goversion
grafana
grv
gx
gx-go
hcloud
hivemind
httpstat
hub
immortal
influxdb
ipfs-cluster
jid
kbfs
keybase
kubectl
kubernetes
kurly
lazygit
lf
licensechecker
lsp
massren
micro
microhookd
miniflux
minify
minikube
minio
mirrorbits
mongo-tools
ncdns
nncp
node_exporter
packer
pam_netauth
peco
pong-command
prometheus
pup
rancher-compose
rclone
rest-server
restic
rocker
runc
ryzen-stabilizator
searchfile
shfmt
sift
skopeo
slack-term
slit
spreed-webrtc
svctl
syncthing
syncthing-inotify
syncthing-relaysrv
tag
terraform
terragrunt
tinycron
umoci
usql
vault
vndr
webcat
websocketd
wego
wireguard-go
xurls
yq-go
```

Failed builds:
```
dnscrypt-proxy
=> ERROR: dnscrypt-proxy-2.0.16_2: cannot be built, it's currently broken; see the build log:
=> ERROR: dnscrypt-proxy-2.0.16_2: go-1.11/runtime.support_avx2

gopass
=> ERROR: gopass-1.8.2_2: cannot be built, it's currently broken; see the build log:
=> ERROR: gopass-1.8.2_2: go-1.11/runtime.support_avx2

hugo
=> ERROR: hugo-0.48_2: cannot be built, it's currently broken; see the build log:
=> ERROR: hugo-0.48_2: go: error loading module requirements

lxd
=> ERROR: lxd-3.2_2: cannot be built, it's currently broken; see the build log:
=> ERROR: lxd-3.2_2: failing to compile with go-1.11

madonctl
/usr/lib/go/pkg/tool/linux_amd64/compile -o $WORK/b002/_pkg_.a -trimpath $WORK/b002 -p github.com/McKael/madonctl/cmd -complete -buildid H_8CJN4qkUmWzDQ8Iv-o/H_8CJN4qkUmWzDQ8Iv-o -goversion go1.11 -D "" -importcfg $WORK/b002/importcfg -pack -c=4 ./accounts.go ./completion.go ./config.go ./domainblocks.go ./emojis.go ./instance.go ./lists.go ./madon.go ./media.go ./notifications.go ./oauth2.go ./root.go ./search.go ./status.go ./stream.go ./timelines.go ./toot.go ./utils.go ./version.go
# github.com/McKael/madonctl/cmd
_build-madonctl-xbps/src/github.com/McKael/madonctl/cmd/accounts.go:656:39: too many arguments in call to gClient.UpdateAccount
	have (*string, *string, *string, *string, *bool)
	want (madon.UpdateAccountParams)
_build-madonctl-xbps/src/github.com/McKael/madonctl/cmd/toot.go:150:27: too many arguments in call to gClient.PostStatus
	have (string, int64, []int64, bool, string, string)
	want (madon.PostStatusParams)
=> ERROR: madonctl-2.3.1_2: do_build: 'go get -x -tags "${go_build_tags}" -ldflags "${go_ldflags}" ${go_package}' exited with 2
=> ERROR:   in do_build() at common/build-style/go.sh:22

nomad
=> ERROR: nomad-0.8.4_2: cannot be built, it's currently broken; see the build log:
=> ERROR: nomad-0.8.4_2: go-1.11/runtime.support_avx2
```

**Comment by the-maldridge** [comment]
Looks fine to me, I'll merge after new ISOs are built.
