### ISSUE TITLE
batman-adv14: does not build with kernels 4.14 and 4.18

### ISSUE THREAD

**Issue by wAmpIre** [void-linux/void-packages#5029]
### System

* xuname:  
  `Void 4.18.19_1 x86_64 GenuineIntel/KVM uptodate rF`
* package:  
  `batman-adv14-2013.4.0_8`

### Expected behavior
- Should compile with newer kernels
- 4.9 works
- 4.14 and 4.18 don't work
- "gluon" guys already fixed this (de facto upstream/maintainer for "batman-adv-legacy")

### Actual behavior
```
$ /var/lib/dkms/batman-adv14/2013.4.0/build/make.log
DKMS make.log for batman-adv14-2013.4.0 for kernel 4.18.19_1 (x86_64)
Thu Nov 22 21:09:09 CET 2018
/var/lib/dkms/batman-adv14/2013.4.0/build/gen-compat-autoconf.sh /var/lib/dkms/batman-adv14/2013.4.0/build/compat-autoconf.h
make -C /lib/modules/4.18.19_1/build M=/var/lib/dkms/batman-adv14/2013.4.0/build PWD=/var/lib/dkms/batman-adv14/2013.4.0/build modules
make[1]: Entering directory '/usr/src/kernel-headers-4.18.19_1'
  CC [M]  /var/lib/dkms/batman-adv14/2013.4.0/build/compat.o
  CC [M]  /var/lib/dkms/batman-adv14/2013.4.0/build/bat_iv_ogm.o
  CC [M]  /var/lib/dkms/batman-adv14/2013.4.0/build/bitarray.o
  CC [M]  /var/lib/dkms/batman-adv14/2013.4.0/build/bridge_loop_avoidance.o
  CC [M]  /var/lib/dkms/batman-adv14/2013.4.0/build/debugfs.o
/var/lib/dkms/batman-adv14/2013.4.0/build/bridge_loop_avoidance.c: In function 'batadv_bla_send_claim':
/var/lib/dkms/batman-adv14/2013.4.0/build/bridge_loop_avoidance.c:354:12: error: 'struct net_device' has no member named 'last_rx'
  soft_iface->last_rx = jiffies;
            ^~
make[2]: *** [scripts/Makefile.build:317: /var/lib/dkms/batman-adv14/2013.4.0/build/bridge_loop_avoidance.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:1505: _module_/var/lib/dkms/batman-adv14/2013.4.0/build] Error 2
make[1]: Leaving directory '/usr/src/kernel-headers-4.18.19_1'
make: *** [Makefile:53: all] Error 2
```

### Steps to reproduce the behavior
```
$ xbps-install batman-adv14
$ dkms remove batman-adv14/2013.4.0  --all
$ dkms install batman-adv14/2013.4.0 --force
```

### (Quick) Fix
```
$ cd /usr/src/
$ mv batman-adv14-2013.4.0/ batman-adv14-2013.4.0.orig
$ git clone https://github.com/freifunk-gluon/batman-adv-legacy.git batman-adv14-2013.4.0
$ dkms install batman-adv14/2013.4.0 --force
$ rmmod batman_adv
$ modprobe batman_adv
$ modinfo batman_adv
filename:       /lib/modules/4.18.19_1/updates/net/batman-adv/batman-adv.ko.gz
version:        2013.4.0-57-g7b775e9-dirty
description:    B.A.T.M.A.N. advanced
author:         Marek Lindner <lindner_marek@yahoo.de>, Simon Wunderlich <siwu@hrz.tu-chemnitz.de>
license:        GPL
srcversion:     6BE331B15F45BE7CF3320F2
depends:        libcrc32c,crc16
retpoline:      Y
name:           batman_adv
vermagic:       4.18.19_1 SMP preempt mod_unload modversions

```

**Comment by biopsin** [comment]
Still a issue or is this resolved moving to batman-adv-2019.5 maybe ?

**Comment by ericonr** [comment]
@Gottox should we maybe update batman-adv14?
