### ISSUE TITLE
Calibre stops working after Qt6 update

### ISSUE THREAD

**Issue by pvvrd** [void-linux/void-packages#43938]
### Is this a new report?

Yes

### System Info

Void 6.1.28_1 x86_64 GenuineIntel uptodate rrmFFFFFFF

### Package(s) Affected

calibre-6.13.0_3

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

No report exists with upstream, however the exact same issue was reported at the Artix Linux forum in https://forum.artixlinux.org/index.php/topic,5337.0/prev_next,next.html

### Expected behaviour

Was expecting calibre to launch.

### Actual behaviour

Calibre crashed, Terminal output as follows:

Failed to import PyQt module: PyQt6.QtNetwork with error: /usr/lib/python3.11/site-packages/PyQt6/QtNetwork.abi3.so: undefined symbol: _ZN16QNetworkDatagram7destroyEP23QNetworkDatagramPrivate, version Qt_6
Traceback (most recent call last):
  File "/usr/bin/calibre", line 21, in <module>
    sys.exit(calibre())
             ^^^^^^^^^
  File "/usr/lib/calibre/calibre/gui_launch.py", line 72, in calibre
    from calibre.gui2.main import main
  File "/usr/lib/calibre/calibre/gui2/__init__.py", line 13, in <module>
    from qt.core import (
ImportError: cannot import name 'QNetworkProxyFactory' from 'qt.core' (/usr/lib/calibre/qt/core.py)

### Steps to reproduce

1. Fully update system using xbps-install -Su
2. Try to run Calibre.

**Comment by crater2150** [comment]
I had the same issue with qutebrowser (from git, current release doesn't fully work with PyQt6 yet).
It can be reproduced with `python -c 'import PyQt6.QtNetwork'`

Rebuilding `python3-pyqt6-network` with xbps-src and reinstalling seems to fix it, so it looks like the package on the mirror is broken?
