### PR TITLE
go: update to 1.27.1.

### PR DESCRIPTION
**Pull request by thypon**
#### Testing the changes
- I tested the changes in this PR: **NO**

Version bump 1.26.5 → 1.27.1.

### CODE REVIEW

**Comment by classabbyamp** [comment]
I believe @the-maldridge wanted to do a go world rebuild for this

**Comment by thypon** [comment]
I'll wait for that then. `terragrunt` is stuck on this update.

**Comment by thypon** [comment]
**Results of the 1.26.5-vs-1.27.1 comparison** —

- **7 packages broken by the go 1.27.1 update**: anubis, fs-repo-migrations, goreleaser, kubo, minio, opentofu, sops
- 11 failures are pre-existing (SHA mismatches on upstream tarballs like croc/soju/docker-machine, chromium elfutils conflict, qmake failures...) — excluded from the report
- kops (skipped as arch-broken) actually builds fine with 1.26.5 — also listed

**1. `x/net/http2.TrailerPrefix` removed by go 1.27**
```
google.golang.org/grpc@v1.8x/internal/transport/handler_server.go:271:18: undefined: http2.TrailerPrefix
```
- Go 1.27 redirects `x/net/http2` to the stdlib copy, where `TrailerPrefix` no longer exists (moved to `net/http.TrailerPrefix`). Fix: bump grpc + x/net upstream.
- Affected packages: **goreleaser** (grpc v1.80.0), **opentofu** (grpc v1.79.3), **sops** (grpc v1.81.0)

**2. `klauspost/cpuid/v2` runtime linkname**
```
link: github.com/klauspost/cpuid/v2: invalid reference to runtime.sched_getaffinity
```
- Go 1.27 tightened restrictions on `//go:linkname` into the runtime; old cpuid/v2 grabs `runtime.sched_getaffinity`. Fix: bump cpuid/v2 (fs-repo-migrations is fully vendored, so a template-level patch or vendored bump is needed).
- Affected packages: **minio** (2021.04.06), **fs-repo-migrations**

**3. `cockroachdb/swiss` runtime intrinsics**
```
github.com/cockroachdb/swiss@v0.0.0-20251224.../map.go:286:7: undefined: hashFn
(+ getRuntimeHasher, fastrand64)
```
- Same class: swiss depends on internal runtime/linkname symbols that changed in 1.27; needs a newer swiss snapshot.
- Affected packages: **kubo**

**4. codegen tooling regression**
```
stringer: internal error: package "errors" without types was imported from "github.com/TecharoHQ/anubis/internal/dnsbl"
=> ERROR: anubis-1.25.0_1: pre_build: 'CGO_ENABLED=0 GOARCH= npm run assets' exited with 1
```
- `stringer` (run during pre_build asset generation) hits an internal error with go 1.27's type-checker; the npm step just inherits the failure. Upstream stringer/gocodegen or template workaround needed.
- Affected packages: **anubis**

**Comment by classabbyamp** [comment]
what was used to generate this comparison?

**Comment by thypon** [comment]
My usual setup, GLM-5.3-flash + opencode. Sometimes run locally, sometimes not.

https://github.com/thypon/dotconfig/tree/master/common/.config/opencode

**Comment by thypon** [comment]
I bumped anubis/goreleaser, and sops. Since the fixes are easy. The rest are broken on `1.27.x` releases

**Comment by classabbyamp** [comment]
I'd like to remind you of [the contributing policy](https://github.com/void-linux/.github/blob/master/CONTRIBUTING.md#ai-usage)

> All contributions are expected to be made by humans. AI tools may be used for research and learning, but all content in contributions must originate from and be understood by the contributor. **This includes** code, documentation, issues, security reports, **pull request descriptions, and comments** in all Void Linux community spaces.

I'm not going to bother wading through a wall of llm-generated text

**Comment by thypon** [comment]
The generated wall of text is well understood, and vouched by me and my tools.

**Comment by classabbyamp** [comment]
the policy's pretty clear that the text itself shouldn't be generated, whether you vouch/understand it or not

**Comment by thypon** [comment]
👍 https://github.com/void-linux/void-packages/pull/62482
