### ISSUE TITLE
[Tracking] linux 5.0 dkms status

### ISSUE THREAD

**Issue by Hoshpak** [void-linux/void-packages#9699]
These dkms modules are important and their compatibility with a kernel version is relevant for the decision to move the default kernel version:

- [x] nvidia (compilation and runtime tested)
- [x] nvidia390
- [x] nvidia340 (compilation and runtime tested)
- [x] zfs (compilation and runtime tested, waiting for release notes update)
- [x] virtualbox-ose (compilation and runtime tested)

If you are using any of these modules, please consider contributing to this issue by installing `linux5.0` and `linux5.0-headers` and report if everything still works for you.

**Comment by pullmoll** [comment]
`linux5.0-5.0.1` and `zfs` works for me.
It seems the system startup is taking (noticeably) more time compared with linux4.19, though.

**Comment by steinex** [comment]
nvidia is working.

**Comment by abenson** [comment]
nvidia390 is working

**Comment by pullmoll** [comment]
These are not building out of the box:
- [ ] exfat-dkms 
      missing definition for `MS_RDONLY`
- [ ] rtl8812au-dkms
      C90 does not support variable length arrays and undefined functions like `get_monotonic_boottime`

**Comment by Johnnynator** [comment]
>     * [ ]  exfat-dkms
>       missing definition for `MS_RDONLY`

https://github.com/dorimanx/exfat-nofuse/issues/145

>     * [ ]  rtl8812au-dkms
>       C90 does not support variable length arrays and undefined functions like `get_monotonic_boottime`

Should be fixed in master, updating the used git revision should work

**Comment by pullmoll** [comment]
exfact-dkms: will try the patch and push it, if it works.
rtl8812au-dkms: Some things are fixed in master while a function or macro in `os_dep/linux/rtw_android.c:603` still fails due to a change of parameters in `static inline bool __chk_range_not_ok(unsigned long addr, unsigned long size, unsigned long limit)`. I gave up on trying to fix this.

**Comment by pullmoll** [comment]
The exfat-dkms patch is not sufficient:
```
/var/lib/dkms/exfat/1.2.8/build/exfat_oal.c: In function 'tm_current':
/var/lib/dkms/exfat/1.2.8/build/exfat_oal.c:137:2: error: implicit declaration of function 'ktime_get_re
al_ts'; did you mean 'ktime_get_real_ns'? [-Werror=implicit-function-declaration]
  ktime_get_real_ts(&ts);
  ^~~~~~~~~~~~~~~~~
  ktime_get_real_ns
```

**Comment by pullmoll** [comment]
IMO `exfat-dkms` and `rtl8812au-dkms` are no show stoppers. Some people (like me :) will have trouble getting their USB wlan sticks working after the kernel switch, but then they can go and boot the 4.19 kernel or buy something else which is supported out of the box.

**Comment by renatoaguiar** [comment]
I verified that latest git revision of rtl8812au-dkms (https://github.com/void-linux/void-packages/pull/10508) works with linux 5.0.5.

**Comment by ackalker** [comment]
One month has passed. Any updates on what could still be blocking the 5.0 switch?

**Comment by Hoshpak** [comment]
ZFS hasn't released a stable version that is officially compatible with the stable kernel version yet and @Vaelatern insists on waiting for that.

**Comment by ackalker** [comment]
Thanks for the info, @Hoshpak .
Oww, what a can of worms this ZFS business appears to be!
Is [this Phoronix report](https://www.phoronix.com/scan.php?page=news_item&px=ZFS-On-Linux-0.7.13-Released) on the release of ZFS On Linux 0.7.13 (claiming support for Linux 5.0) any reason for hope in this regard, or is it now a matter of a waiting game for one of the parties to budge and give in? I sure hope I can hold my breath for that long :)

**Comment by Hoshpak** [comment]
It isn't related to these issues. The issue is just that ZOL 0.7.13 only states compatibility with 5.0rc3 and not 5.0 release. So we have to wait for a release that officially supports 5.0 which will most likely be 0.8.0 since the RC of ZOL already states support.

**Comment by ackalker** [comment]
@Hoshpak Thanks again. I guess we'll just have to wait and see then.

**Comment by Hoshpak** [comment]
5.0 is EOL and will be removed from the repository soon.
