### PR TITLE
[WIP] LLVM 15

### PR DESCRIPTION
**Pull request by tranzystorek-io**
[ci skip]

TODO:

- [ ] Adjust patches marked as `.patch.skip`

### CODE REVIEW

**Comment by tranzystorek-io** [comment]
For now working on top of #34902

**Comment by dkwo** [comment]
You may want to look at the previous PR (for 14) for inspiration, as well as chimera and alpine for patches.
Some stuff will need rebuild (e.g. mesa), and maybe update zig to 10.

File: srcpkgs/llvm15/template [hunk 1]
```diff
@@ -0,0 +1,434 @@
...
+homepage="https://www.llvm.org"
+distfiles="https://github.com/llvm/llvm-project/releases/download/llvmorg-${version}/llvm-project-${version}.src.tar.xz"
+checksum=9c4278a6b8884eb7f4ae7dfe3c8e5445019824885e47cfdf1392563c47316fd6
+lib32disabled=yes
+python_version=3
+
+if [ "$XBPS_TARGET_LIBC" = "musl" ]; then
+	configure_args+=" -DLIBCXX_HAS_MUSL_LIBC=YES"
+	makedepends+=" libexecinfo-devel"
+	depends+=" libexecinfo-devel"
```
Comment (oreo639) [inline srcpkgs/llvm15/template:44]: libexecinfo in LLVM is optional. Don't enable it. (it doesn't work)

**Comment by Vaelatern** [comment]
```
diff --git a/srcpkgs/zig/template b/srcpkgs/zig/template
index 728c5a64e9d..f453348a7a0 100644
--- a/srcpkgs/zig/template
+++ b/srcpkgs/zig/template
@@ -1,7 +1,7 @@
 # Template file for 'zig'
 pkgname=zig
-version=0.8.1
-revision=2
+version=0.10.0
+revision=1
 archs="x86_64* aarch64*"
 build_style=cmake
 make_cmd=make
@@ -11,7 +11,7 @@ maintainer="Isaac Freund <mail@isaacfreund.com>"
 license="MIT"
 homepage="https://ziglang.org"
 distfiles="https://ziglang.org/download/${version}/zig-${version}.tar.xz"
-checksum=8c428e14a0a89cb7a15a6768424a37442292858cdb695e2eb503fa3c7bf47f1a
+checksum=d8409f7aafc624770dcd050c8fa7e62578be8e6a10956bca3c86e8531c64c136
 nopie=yes
 nocross=yes

```

Could use the update :)

File: srcpkgs/llvm15/template [hunk 2]
```diff
@@ -0,0 +1,434 @@
+# Template file for 'llvm15'
+pkgname=llvm15
+version=15.0.6
+revision=1
```
Comment (paper42) [inline srcpkgs/llvm15/template:4]: this should be in a separate commit, "New package: llvm15-15.0.6"

File: srcpkgs/llvm/template [hunk 3]
```diff
@@ -1,11 +1,11 @@
...
 revision=1
 build_style=meta
-depends="llvm12"
-replaces="llvm11>=0 llvm10>=0 llvm9>=0 llvm8>=0 llvm7>=0 llvm6.0>=0 llvm3.9>=0"
+depends="llvm15"
 short_desc="LLVM meta package"
 maintainer="Enno Boland <gottox@voidlinux.org>"
 license="Public Domain"
 homepage="https://www.voidlinux.org"
+replaces="llvm12>=0 llvm11>=0 llvm10>=0 llvm9>=0 llvm8>=0 llvm7>=0 llvm6.0>=0 llvm3.9>=0"
```
Comment (oreo639) [inline srcpkgs/llvm/template:11]: llvm12 currently provides clang et al, which should be removed:
https://github.com/void-linux/void-packages/commit/0d9f8330b556561ee38de7d6a0d4280f56cdd58e

Also, you need to rebuild/update everything depending on llvm.

Here is the llvm12 update for reference:
https://github.com/void-linux/void-packages/commits/e8c2d0e32888730ad5fa16e1441de1a4e1a3a64a

Ofc a bunch of stuff was updated after that (i.e. rust, ldc, etc) but just for reference.

**Comment by oreo639** [comment]
Here is a patch to fix building on musl:
https://gist.github.com/oreo639/a43b23916774fe58910bffce6a848190

It includes a patch that partially reverts:
https://github.com/llvm/llvm-project/commit/67b0b02ec9f2bbc57bf8f0550828d97f460ac11f

That is necessary to fix usage of abi_tag() on an extern "C" declaration which is explicitly not allowed in gcc:
https://github.com/gcc-mirror/gcc/blob/master/gcc/cp/tree.cc#L5350-L5355

This also disables GWP-ASan/`-fsanitize=scudo` since it depends on the broken libexecinfo and GWP-ASan also gets into an infinite loop on musl.

**Comment by simvux** [comment]
I believe this is required for mesa to work correctly with the new rx 7000s series amd GPU's. So to make them plug ń play we'll need to both merge this and swap the depedency in `mesa` from `llvm` to `llvm15`. 

FWIW; merging this branch into #41084 and changing #41084 to `llvm15` worked for me, but I also needed to fetch the latest `linux-firmware-amd` blobs, update `SPIRV-{Headers,LLVM-Translator}`, hack some stuff into `shlibs` which I'm not familiar with.

**Comment by oreo639** [comment]
llvm is llvm15 in this PR. mesa just needs to be rebuilt.

**Comment by ardadem** [comment]
SPIRV-LLVM-Translator should match the llvm version so please update that as well.

**Comment by dkwo** [comment]
Perhaps it's better to also update river and waylock.
I've been using them with static zig for a while, with no issues. Just for reference:
```
 # Template file for 'river'
 pkgname=river
-version=0.1.1
-revision=2
+version=0.2.2
+revision=1
 build_style=zig-build
-configure_args="$(vopt_if xwayland -Dxwayland)"
+configure_args="$(vopt_if xwayland -Dxwayland) -Dpie -Dstrip"
 hostmakedepends="pkg-config wayland-devel scdoc"
-makedepends="wlroots0.15-devel libevdev-devel"
+makedepends="wlroots-devel libevdev-devel pixman-devel
+ wayland-protocols"
 depends="$(vopt_if xwayland xorg-server-xwayland)"
 short_desc="Dynamic tiling Wayland compositor"
 maintainer="Isaac Freund <mail@isaacfreund.com>"
 license="GPL-3.0-or-later"
 homepage="https://github.com/riverwm/river"
 distfiles="${homepage}/releases/download/v${version}/river-${version}.tar.gz"
-checksum=2a0bcd4670ed9ebd39c279f2bf10803fc65c9f3ee2307ce40728df23ce914d18
+checksum=99c256c6b1461d9beeff95fae0db54403e2b12f96e4c959ddbcaeae73fd89091

 build_options="xwayland"
 build_options_default="xwayland"
```
with no patch, as well as
```
 # Template file for 'waylock'
 pkgname=waylock
-version=0.3.5
+version=0.6.1
 revision=1
-build_style=cargo
+build_style=zig-build
+configure_args="-Dpie -Dstrip -Drelease-safe"
 hostmakedepends="pkg-config"
-makedepends="libxkbcommon-devel pam-devel"
+makedepends="libxkbcommon-devel pam-devel wayland-protocols wayland-devel scdoc"
 short_desc="Simple screenlocker for wayland compositors"
 maintainer="Isaac Freund <ifreund@ifreund.xyz>"
-license="MIT"
+license="ISC"
 homepage="https://github.com/ifreund/waylock"
-distfiles="${homepage}/archive/v${version}.tar.gz"
-checksum=60abf78ae8aa9c28f3230f157607fbd74250a51322776ad1b7abed1408432b87
+distfiles="https://github.com/ifreund/waylock/releases/download/v${version}/waylock-${version}.tar.gz"
+checksum=4d3fc46b0f48c964362fdfceff27314a87b28cb3c40fbf782d24ca755bfa8c55
 
 post_install() {
        vlicense LICENSE
```

**Comment by Johnnynator** [comment]
I did some fixes for cross, also I don't think we need the per target runtime dirs, and if we did use them you should probably use a wildcard in vinstall

```diff
diff --git a/srcpkgs/llvm15/template b/srcpkgs/llvm15/template
index db510bbd24..6249ec307c 100644
--- a/srcpkgs/llvm15/template
+++ b/srcpkgs/llvm15/template
@@ -4,6 +4,7 @@ version=15.0.6
 revision=1
 build_wrksrc=llvm
 build_style=cmake
+_ext_suffix=".cpython-${py3_ver/./}-linux-${XBPS_TARGET_LIBC/glibc/gnu}.so"
 configure_args="
  -DCMAKE_BUILD_TYPE=Release -Wno-dev
  -DENABLE_LINKER_BUILD_ID=YES
@@ -23,11 +24,15 @@ configure_args="
  -DLLVM_LINK_LLVM_DYLIB=YES
  -DLLVM_ENABLE_RTTI=YES
  -DLLVM_ENABLE_FFI=YES
- -DLLVM_BINUTILS_INCDIR=/usr/include"
+ -DLLVM_BINUTILS_INCDIR=/usr/include
+ -DLLVM_ENABLE_PER_TARGET_RUNTIME_DIR=NO
+ -DLLDB_PYTHON_RELATIVE_PATH=lib/python${py3_ver}/site-packages
+ -DLLDB_PYTHON_EXE_RELATIVE_PATH=bin/python${py3_ver}
+ -DLLDB_PYTHON_EXT_SUFFIX=$_ext_suffix"
 hostmakedepends="perl python3 zlib-devel libffi-devel swig python3-Sphinx
  python3-recommonmark python3-sphinx-automodapi"
 makedepends="python3-devel zlib-devel elfutils-devel libffi-devel libedit-devel
  libxml2-devel binutils-devel libatomic-devel"
 depends="libllvm15>=${version}_${revision}"
 short_desc="Low Level Virtual Machine"
 maintainer="Orphaned <orphan@voidlinux.org>"
@@ -56,7 +61,7 @@ _libomp_enable=no
 
 case "$XBPS_TARGET_MACHINE" in
        ppc64le*) ;;
-       ppc*|i686*) _lldb_enable=no ;;
+       ppc*|i686*|riscv64*) _lldb_enable=no ;;
 esac
 
 case "$XBPS_TARGET_MACHINE" in
@@ -153,9 +158,14 @@ pre_configure() {
                        -DLLVM_ENABLE_PROJECTS=${_enabled_projects}
                make ${makejobs} -C utils/TableGen
                make ${makejobs} -C tools/clang/utils/TableGen
+               make ${makejobs} -C tools/clang/tools/extra/clang-tidy/misc/ConfusableTable
+               make ${makejobs} -C tools/clang/tools/extra/pseudo/gen
                [ "$_lldb_enable" = "yes" ] && make ${makejobs} -C tools/lldb/utils/TableGen
                configure_args+=" -DLLVM_TABLEGEN=${wrksrc}/llvm/build/HOST/bin/llvm-tblgen"
                configure_args+=" -DCLANG_TABLEGEN=${wrksrc}/llvm/build/HOST/bin/clang-tblgen"
+               configure_args+=" -DCLANG_TIDY_CONFUSABLE_CHARS_GEN=${wrksrc}/llvm/build/HOST/bin/clang-tidy-confusable-chars-gen"
+               configure_args+=" -DCLANG_PSEUDO_GEN=${wrksrc}/llvm/build/HOST/bin/clang-pseudo-gen"
+               [ "$_lldb_enable" = "yes" ] && configure_args+=" -DLLDB_TABLEGEN=${wrksrc}/llvm/build/HOST/bin/lldb-tblgen"
                [ "$_lldb_enable" = "yes" ] && configure_args+=" -DLLDB_TABLEGEN=${wrksrc}/llvm/build/HOST/bin/lldb-tblgen"
                cd ../..
        fi
@@ -298,9 +308,9 @@ lld_package() {
        short_desc+=" - linker"
        homepage="https://lld.llvm.org"
        pkg_install() {
-               vmove usr/bin/ld.lld*
-               vmove usr/bin/ld64.lld*
-               vmove usr/bin/lld*
+               vmove "usr/bin/ld.lld*"
+               vmove "usr/bin/ld64.lld*"
+               vmove "usr/bin/lld*"
                vmove usr/bin/wasm-ld
                vmove usr/share/doc/LLVM/lld
        }
@@ -324,9 +334,9 @@ lldb_package() {
        short_desc+=" - LLDB debugger"
        homepage="https://lldb.llvm.org/"
        pkg_install() {
-               vmove usr/bin/*lldb*
-               vmove usr/lib/liblldb*so.*
-               vmove /usr/lib/python*
+               vmove "usr/bin/*lldb*"
+               vmove "usr/lib/liblldb*so.*"
+               vmove usr/lib/python*
        }
 }
 
@@ -343,7 +353,7 @@ lldb-devel_package() {
 llvm-libunwind_package() {
        short_desc+=" - libunwind"
        pkg_install() {
-               vmove "usr/lib/${XBPS_TRIPLET}/libunwind.so.*"
+               vmove "usr/lib/libunwind.so.*"
        }
 }
 
@@ -354,8 +364,8 @@ llvm-libunwind-devel_package() {
        pkg_install() {
                vmove usr/include/mach-o
                vmove "usr/include/*unwind*"
-               vmove "usr/lib/${XBPS_TRIPLET}/libunwind.a"
-               vmove "usr/lib/${XBPS_TRIPLET}/libunwind.so"
+               vmove "usr/lib/libunwind.a"
+               vmove "usr/lib/libunwind.so"
                vmove usr/share/doc/LLVM/libunwind
        }
 }
@@ -363,7 +373,7 @@ llvm-libunwind-devel_package() {
 libcxxabi_package() {
        short_desc+=" - low level support for libc++"
        pkg_install() {
-               vmove "usr/lib/${XBPS_TRIPLET}/libc++abi.so.*"
+               vmove "usr/lib/libc++abi.so.*"
        }
 }
 
@@ -372,15 +382,15 @@ libcxxabi-devel_package() {
        depends="libcxxabi>=${version}_${revision}"
        pkg_install() {
                vmove "usr/include/*cxxabi*"
-               vmove "usr/lib/${XBPS_TRIPLET}/libc++abi.so"
-               vmove "usr/lib/${XBPS_TRIPLET}/libc++abi.a"
+               vmove "usr/lib/libc++abi.so"
+               vmove "usr/lib/libc++abi.a"
        }
 }
 
 libcxx_package() {
        short_desc+=" - C++ standard library"
        pkg_install() {
-               vmove "usr/lib/${XBPS_TRIPLET}/libc++.so.*"
+               vmove "usr/lib/libc++.so.*"
        }
 }
 
@@ -389,9 +399,9 @@ libcxx-devel_package() {
        depends="libcxx>=${version}_${revision}"
        pkg_install() {
                vmove usr/include/c++
-               vmove "usr/lib/${XBPS_TRIPLET}/libc++.so"
-               vmove "usr/lib/${XBPS_TRIPLET}/libc++.a"
-               vmove "usr/lib/${XBPS_TRIPLET}/libc++experimental.a"
+               vmove "usr/lib/libc++.so"
+               vmove "usr/lib/libc++.a"
+               vmove "usr/lib/libc++experimental.a"
                vmove usr/share/doc/LLVM/libcxx
        }
 }
```

File: srcpkgs/llvm15/template [hunk 4]
```diff
@@ -0,0 +1,437 @@
...
+			cmake ../.. -DCMAKE_BUILD_TYPE=Release \
+			-DLLVM_ENABLE_PROJECTS=${_enabled_projects}
+		make ${makejobs} -C utils/TableGen
+		make ${makejobs} -C tools/clang/utils/TableGen
+		make ${makejobs} -C tools/clang/tools/extra/clang-tidy/misc/ConfusableTable
+		make ${makejobs} -C tools/clang/tools/extra/pseudo/gen
+		[ "$_lldb_enable" = "yes" ] && make ${makejobs} -C tools/lldb/utils/TableGen
+		configure_args+=" -DLLVM_TABLEGEN=${wrksrc}/llvm/build/HOST/bin/llvm-tblgen"
+		configure_args+=" -DCLANG_TABLEGEN=${wrksrc}/llvm/build/HOST/bin/clang-tblgen"
+		configure_args+=" -DCLANG_TIDY_CONFUSABLE_CHARS_GEN=${wrksrc}/llvm/build/HOST/bin/clang-pseudo-gen"
```
Comment (Johnnynator) [inline srcpkgs/llvm15/template:166]:
```suggestion
		configure_args+=" -DCLANG_TIDY_CONFUSABLE_CHARS_GEN=${wrksrc}/llvm/build/HOST/bin/clang-tidy-confusable-chars-gen"
```

It seems like confusable chars did get confused slightly.

**Comment by oreo639** [comment]
The libclc tests fail on every distro afaict (at least on Debian, Fedora, and Alpine) LLVM upstream's CI compiles with everything enabled except clspv and doesn't run those tests.

**Comment by simvux** [comment]
Thank you for all your work on this <3 

Looking forward to seeing it in my `xi -Su`

**Comment by cmueller-tp** [comment]
Will this be abandoned again once they tag the 16.0 as stable? They've already tagged RC2 2 weeks ago.

**Comment by motorto** [comment]
Missing a review only, right ? Or anything I could try to help ?

**Comment by tranzystorek-io** [comment]
> Did a git bisect on the 32bit arm build failure.
> 
> It broke with the following commit [llvm/llvm-project@425620c](https://github.com/llvm/llvm-project/commit/425620ccdd47e56b59512913cdc71e116f951e4e) but I'm unsure on how to fix it correctly.
> 
> ```
> /usr/lib/gcc/armv7l-linux-gnueabihf/12.2.0/../../../../armv7l-linux-gnueabihf/bin/ld: projects/libcxx/src/CMakeFiles/cxx_shared.dir/locale.cpp.o: in function `std::__1::__time_get_c_storage<char>::__x() const [clone .localalias]':
> locale.cpp:(.text._ZNKSt3__120__time_get_c_storageIcE3__xEv+0xb4): undefined reference to `std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()'
> /usr/lib/gcc/armv7l-linux-gnueabihf/12.2.0/../../../../armv7l-linux-gnueabihf/bin/ld: projects/libcxx/src/CMakeFiles/cxx_shared.dir/locale.cpp.o: in function `std::__1::__time_get_c_storage<char>::__X() const [clone .localalias]':
> ```
> 
> Build log: https://gist.github.com/Johnnynator/e9dddc63100c212303fb81aa27cc39f6

This is still unresolved, I'll add it to the TODO list.

**Comment by ihameed** [comment]
The 32-bit ARM failure is caused by https://gcc.gnu.org/bugzilla/show_bug.cgi?id=109180. Some immediate options:
1. patch libc++: https://gist.github.com/ihameed/b226d72537e8a4a8e9c590bef529a137, or
2. build libc++ with clang by using `-DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind"` instead of `-DLLVM_ENABLE_PROJECTS="...;libcxx;libcxxabi;libunwind;..."`.

**Comment by oreo639** [comment]
ihameed, tysm for looking into it. I can confirm that adding `-fno-inline` to the compile flags for string.cpp does indeed allow llvm15 to compile on arm:
https://gist.github.com/oreo639/7c59c0576ecc4378dbebbe3c2730fdfe

Also, @tranzystorek-io can you add back the description for the libcxxabi-musl patch (or at least have some kind of description for it):
> gcc does not support using abi_tag in an extern "C" declaration:
> https://github.com/gcc-mirror/gcc/blob/cf59c8983ef6590f0d69014f8dc8778b5b7691c6/gcc/cp/tree.cc#L5354-L5359

**Comment by simvux** [comment]
@tranzystorek-io @leahneukirchen the build of LLVM15 & Friends failed and the active LLVM version in the xbps repository is still 12 even though it's been 15 in the github repository for days. Is this a known problem right now?

**Comment by tranzystorek-io** [comment]
@simvux this is a problem with repo-default, it hasn't been syncing up properly for sometime, to work around switch to repo-de

**Comment by simvux** [comment]
ah i see, thanks!
