### ISSUE TITLE
Fixing patch whitespace

### ISSUE THREAD

**Issue by foopub** [void-linux/void-packages#33917]
Regarding 7b4119d.
Seems reasonable to make a list of packages known to have bad patches and verify each build...

- [x]  firefox-esr
- [x] thundrebird

**Comment by foopub** [comment]
I actually get an error with the firefox-esr build, even tho there's no problem with the patching, so can't verify the build works: 

```
=> firefox-esr-78.14.0_1: running do_build ...
Traceback (most recent call last):
  File "/builddir/firefox-78.14.0/./mach", line 235, in <module>
    main(sys.argv[1:])
  File "/builddir/firefox-78.14.0/./mach", line 227, in main
    mach = get_mach()
  File "/builddir/firefox-78.14.0/./mach", line 209, in get_mach
    mach = check_and_get_mach(dir_path)
  File "/builddir/firefox-78.14.0/./mach", line 165, in check_and_get_mach
    return load_mach(dir_path, mach_path)
  File "/builddir/firefox-78.14.0/./mach", line 153, in load_mach
    return mach_bootstrap.bootstrap(dir_path)
  File "/builddir/firefox-78.14.0/build/mach_bootstrap.py", line 203, in bootstrap
    import mach.main
  File "/builddir/firefox-78.14.0/python/mach/mach/main.py", line 19, in <module>
    from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
=> ERROR: firefox-esr-78.14.0_1: do_build: './mach build' exited with 1
=> ERROR:   in do_build() at srcpkgs/firefox-esr/template:169
```

But `cat srcpkgs/firefox-esr/patches/* | grep py` shows no python files so so I guess this error isn't related to the patch? Is it safe check it off here?

**Comment by q66** [comment]
that looks to be an unrelated error

**Comment by paper42** [comment]
It should be `from collections.abc import Iterable`, latest ESR is 91.3.0 which has this fixed. We can either update to it or make a simple patch for the current version.

**Comment by foopub** [comment]
> It should be `from collections.abc import Iterable`, latest ESR is 91.3.0 which has this fixed. We can either update to it or make a simple patch for the current version.

That's just the peak of the iceberg, there's too many errors to fix (I fixed 10 or so the other day before giving up) - better update to 91.3, or build with python 3.9.

**Comment by paper42** [comment]
> > It should be `from collections.abc import Iterable`, latest ESR is 91.3.0 which has this fixed. We can either update to it or make a simple patch for the current version.
> 
> That's just the peak of the iceberg, there's too many errors to fix (I fixed 10 or so the other day before giving up) - better update to 91.3

@Duncaen

> or build with python 3.9.

This is not possible, we are using python 3.10 everywhere.

**Comment by newbluemoon** [comment]
Found another one in openjade, fixed in #33974.

**Comment by newbluemoon** [comment]
pipewire is another one
