### ISSUE TITLE
xpadneo: dkms build fails for linux6.18

### ISSUE THREAD

**Issue by onuronsekiz** [void-linux/void-packages#60430]
### Is this a new report?

Yes

### System Info

Void 6.18.27_1 x86_64 GenuineIntel uptodate rrrrmmnF

### Package(s) Affected

xpadneo-0.9.7_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

https://github.com/atar-axis/xpadneo/issues/575
https://discuss.cachyos.org/t/kernel-6-18-breaks-xpadneo/19455/2

### Expected behaviour

DKMS build should not fail.

### Actual behaviour

DKMS build fails.

### Steps to reproduce

1. Install xpadneo or update kernel to 6.18
2. dkms build fails.

**Comment by onuronsekiz** [comment]
/var/lib/dkms/hid-xpadneo/0.9.7/build/make.log

```
DKMS (dkms-3.3.0) make.log for hid-xpadneo/0.9.7 for kernel 6.18.27_1 (x86_64)
Fri May  8 05:32:14 PM +03 2026

Building module(s)
# command: make -j8 KERNELRELEASE=6.18.27_1 -C '/lib/modules/6.18.27_1/build' M='/var/lib/dkms/hid-xpadneo/0.9.7/build/src' VERSION='0.9.7' modules
make: Entering directory '/usr/src/kernel-headers-6.18.27_1'
make[1]: Entering directory '/var/lib/dkms/hid-xpadneo/0.9.7/build/src'
  CC [M]  hid-xpadneo.o
hid-xpadneo.c: In function 'xpadneo_probe':
hid-xpadneo.c:1196:21: error: implicit declaration of function 'ida_simple_get' [-Wimplicit-function-declaration]
 1196 |         xdata->id = ida_simple_get(&xpadneo_device_id_allocator, 0, 0, GFP_KERNEL);
      |                     ^~~~~~~~~~~~~~
hid-xpadneo.c: In function 'xpadneo_release_device_id':
hid-xpadneo.c:1291:17: error: implicit declaration of function 'ida_simple_remove' [-Wimplicit-function-declaration]
 1291 |                 ida_simple_remove(&xpadneo_device_id_allocator, xdata->id);
      |                 ^~~~~~~~~~~~~~~~~
make[3]: *** [/usr/src/kernel-headers-6.18.27_1/scripts/Makefile.build:287: hid-xpadneo.o] Error 1
make[2]: *** [/usr/src/kernel-headers-6.18.27_1/Makefile:2022: .] Error 2
make[1]: *** [/usr/src/kernel-headers-6.18.27_1/Makefile:248: __sub-make] Error 2
make[1]: Leaving directory '/var/lib/dkms/hid-xpadneo/0.9.7/build/src'
make: *** [Makefile:248: __sub-make] Error 2
make: Leaving directory '/usr/src/kernel-headers-6.18.27_1'

# exit code: 2
# elapsed time: 00:00:02
----------------------------------------------------------------
```

**Comment by classabbyamp** [comment]
would you be able to test this? https://github.com/void-linux/void-packages/pull/60432

**Comment by onuronsekiz** [comment]
I will try it with xbps-src and inform here.

**Comment by onuronsekiz** [comment]
xpadneo-0.10.2 PR installed successfully and appears to be working with kernel6.18.
