### PR TITLE
Raspberry PI Updates

### PR DESCRIPTION
**Pull request by kenrap**
#### Testing the changes
- I tested the changes in this PR: **YES**

#### Local build testing
- I built this PR locally for these architectures:
  - aarch64 (for rpi4)

#### Contributor's notes
- The rpi-kernel package (both the one currently and this updated version) doesn't USB boot without an initramfs.
  - I used dracut to successfully make this work.

### CODE REVIEW

**Comment by kenrap** [comment]
Alright, that should make the rpi-firmware template more maintainable.

**Comment by kenrap** [comment]
Should I bump the `_githash` in `rpi-kernel` to the latest commit?

**Comment by classabbyamp** [comment]
no, see the comment at the top of the template

**Comment by tsjk** [comment]
Cool. I'll test this on my armv6 rpis

**Comment by leahneukirchen** [comment]
If it works with dracut, that suggests some modules are missing to be compiled in? Would this be a better fix?

**Comment by classabbyamp** [comment]
hm but we're using the rpi dotconfigs, so I'd expect usbboot to be working with them

**Comment by tsjk** [comment]
It doesn't build for armv6:

```
...
  CC [M]  crypto/seqiv.mod.o
  CC [M]  crypto/sha256_generic.mod.o
  CC [M]  crypto/sha512_generic.mod.o
arm-linux-gnueabihf-ld: arch/arm/lib/uaccess_with_memcpy.o: in function `__copy_to_user_memcpy':
uaccess_with_memcpy.c:(.text+0x2dc): undefined reference to `__memcpy'
make[1]: *** [scripts/Makefile.vmlinux:34: vmlinux] Error 1
make: *** [Makefile:1255: vmlinux] Error 2
make: *** Waiting for unfinished jobs....
...
```

I used: `xbps-src -a armv6l pkg rpi-kernel`

**Comment by classabbyamp** [comment]
works with 6.1.27:
```diff
diff --git a/srcpkgs/rpi-kernel/template b/srcpkgs/rpi-kernel/template
index 0a2ebaf80a..8fa5a3fcc1 100644
--- a/srcpkgs/rpi-kernel/template
+++ b/srcpkgs/rpi-kernel/template
@@ -13,9 +13,9 @@
 # Upstream documentation: https://www.raspberrypi.com/documentation/computers/linux_kernel.html
 
 pkgname=rpi-kernel
-version=6.1.25
+version=6.1.27
 revision=1
-_githash=e5c93db2b62d983d6a164786357a7eb02c4e50d0
+_githash=83cf6b410113c98ebfd0b7fef70b1a7c9539b0b9
 archs="armv6l* armv7l* aarch64*"
 hostmakedepends="perl kmod uboot-mkimage openssl-devel bc bison flex xz"
 makedepends="ncurses-devel"
@@ -24,7 +24,7 @@ homepage="http://www.kernel.org"
 license="GPL-2.0-only"
 short_desc="Linux kernel for Raspberry Pi (${version%.*} series [git ${_githash:0:7}])"
 distfiles="https://github.com/raspberrypi/linux/archive/${_githash}.tar.gz"
-checksum=b142709b3be0ec13aa7c40bd683f69ee9b84281ed7b95905633237418cf70906
+checksum=be28f607f945ee7083af61608f29ced824db87fc7b49bff4e4c7d64ca8581935
 python_version=3
 
 _kernver="${version}_${revision}"
 ```

**Comment by classabbyamp** [comment]
builds available for ease of testing: https://devspace.voidlinux.org/abby/rpi-kernel-6.1.27/

**Comment by tsjk** [comment]
What's the rationale for the chosen firmware commit?

**Comment by kenrap** [comment]
Because this firmware update allows my rpi4 to POST unlike the one currently available.

**Comment by tsjk** [comment]
It's getting late here now. I've built the stuff. Gonna deploy tomorrow.
You might wanna update userland as well if you're at it. Feel free to just steal https://github.com/void-linux/void-packages/commit/d15ed92d88bf2b047ac463446dd0b676596dcd9b. I'm running it on my armv6l pis.

**Comment by classabbyamp** [comment]
i've updated the builds i linked above

**Comment by tsjk** [comment]
```
Linux rpi 6.1.27_1 #1 Wed May 10 14:23:49 UTC 2023 armv6l GNU/Linux
```

Seems to work here. Gonna see on another unit, which uses wifi drivers compiled with dkms, as well.

**Comment by tsjk** [comment]
dkms fails instantly during upgrade. :(

```
rpi-kernel-6.1.27_1: configuring ...
Executing post-install kernel hook: 10-dkms ...
make: Entering directory '/usr/src/rpi-kernel-headers-6.1.27_1'
  SYNC    include/config/auto.conf.cmd
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  HOSTCC  scripts/kconfig/confdata.o
  HOSTCC  scripts/kconfig/expr.o
  HOSTCC  scripts/kconfig/lexer.lex.o
  HOSTCC  scripts/kconfig/menu.o
  HOSTCC  scripts/kconfig/parser.tab.o
  HOSTCC  scripts/kconfig/preprocess.o
  HOSTCC  scripts/kconfig/symbol.o
  HOSTCC  scripts/kconfig/util.o
  HOSTLD  scripts/kconfig/conf
crypto/Kconfig:1399: can't open file "arch/arm64/crypto/Kconfig"
make[2]: *** [scripts/kconfig/Makefile:77: syncconfig] Error 1
make[1]: *** [Makefile:704: syncconfig] Error 2
make: *** [Makefile:805: include/config/auto.conf.cmd] Error 2
make: *** [include/config/auto.conf.cmd] Deleting file 'include/generated/rustc_cfg'
make: *** [include/config/auto.conf.cmd] Deleting file 'include/generated/autoconf.h'
make: Leaving directory '/usr/src/rpi-kernel-headers-6.1.27_1'
```

**Comment by classabbyamp** [comment]
which pi does this error happen on?

**Comment by tsjk** [comment]
> which pi and arch does this error happen on?

armv6l, and it's a Pi 1B.

In addition, when deleting all ifs except the ARM one, I get an infinite loop:
```
$ doas make -j $(nproc) -C /lib/modules/6.1.27_1/build prepare0
...
HOSTLD  scripts/mod/modpost
scripts/Makefile.build:425: warning: overriding recipe for target 'built-in.a'
Makefile:1259: warning: ignoring old recipe for target 'built-in.a'
scripts/Makefile.build:440: warning: overriding recipe for target 'modules.order'
Makefile:1923: warning: ignoring old recipe for target 'modules.order'
scripts/Makefile.build:425: warning: overriding recipe for target 'built-in.a'
Makefile:1259: warning: ignoring old recipe for target 'built-in.a'
scripts/Makefile.build:440: warning: overriding recipe for target 'modules.order'
Makefile:1923: warning: ignoring old recipe for target 'modules.order'
...
```

Have anyone tested that installing the package works as expected when dkms is installed?
I don't have any dkms-modules as I usually clean them out before kernel upgrades and then reinstall. So the failure is caused by just having dkms.

**Comment by classabbyamp** [comment]
after resetting the edits you made to whichever file, does adding arm_64bit=0 to /boot/config.txt fix it?

**Comment by tsjk** [comment]
> after resetting the edits you made to whichever file, does adding arm_64bit=0 to /boot/config.txt fix it?

I can try. But I haven't rebooted. This happens immediately when the kernel package is upgraded.
The thing is that the ifs in crypto/Kconfig do not work. If I delete the ARM64-clause it fails on the next one (as we strip away all archs except the target's when building the package.

Edit: Adding the directive to /boot/config.txt makes no difference.

**Comment by tsjk** [comment]
I'll revert on that system for now, to rpi-kernel-5.15.92_1.
I guess that one can run
```
make -j $(nproc) -C /lib/modules/6.1.27_1/build prepare0
```
(as root) even without dkms to reproduce the issue. As far as I've gathered the dkms hook fails on that command.

**Comment by tsjk** [comment]
Yeah, we are a bit stuck here.

**Comment by classabbyamp** [comment]
I've made some progress but I've been busy with other things

**Comment by moabeat-berlin** [comment]
I think I figured something out why dkms is not working with the new kernel. There have been some changes how the kernel is configured.  For example, the crypto module got has now dependencies into the "arch" directory. Check this [diff between the old 5.15.72 and the newer 6.1.53](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/diff/crypto/Kconfig?id=v6.1.53&id2=v5.15.72) version.

Now, the dkms with the x86_64 architecture only works due an error in the template script of the "linux6.3" package. [Here](https://github.com/void-linux/void-packages/blob/master/srcpkgs/linux6.3/template#L294) all files related to unnecessary architectures should actually get removed. The case to extend this also to architectures like "powerpc" (matching *p) uses the "arch" variable and expects it either as "i386" or "x86_64". However, this is never true as [here](https://github.com/void-linux/void-packages/blob/master/srcpkgs/linux6.3/template#L119) the "arch" variable is set to "x86". Therefore no "powerpc" directory is removed on x86_64 and dkms works. By accident all necessary sub-directories in the "arch" directory are present.

For "arm64" this is different. Here architectures starting with "p*" are removed. Now the question is, why is this important? Well, something similar is present in the "rpi-kernel" package [here](https://github.com/void-linux/void-packages/blob/master/srcpkgs/rpi-kernel/template#L193). It even removes "arm64" if you are on "arm". And since there is a hard-coded dependency in "crypto/Kconfig" it breaks.

Maybe the best approach is, to not remove any unnecessary architectures at all anymore if there are so many interdependences?

**Comment by leahneukirchen** [comment]
Thanks for the analysis, I think just keeping the headers is the way to go, they are not very big in the end.

**Comment by moabeat-berlin** [comment]
I might be able to submit this as a pull request tomorrow or the day after. I would like to test this first on x86_64, armv6l and aarch64 properly. I have some devices at hand for that. However, since this issue spans across the packages "rpi-kernel" and "linux6.3", would you recommend this as a single PR for this fix or separate ones for each package?

**Comment by leahneukirchen** [comment]
No need to make a PR, the Void kernel maintainers know what to do.  Thanks!

**Comment by tsjk** [comment]
I think I made a similar point in https://github.com/raspberrypi/linux/issues/5468 back in May, but the audience wasn't mature back then. Would be cool to get v6.1 - especially when the previous lts is no longer maintained by the pi people.

**Comment by classabbyamp** [comment]
i'm going to try and work on this PR in the next couple days... I'll finally have the time

**Comment by classabbyamp** [comment]
continuing the party in: https://devspace.voidlinux.org/abby/updates/rpi/
