### PR TITLE
vscode: update to 1.96.4

### PR DESCRIPTION
**Pull request by atk**
#### Testing the changes
- I tested the changes in this PR: **briefly**

### CODE REVIEW

**Comment by slymattz** [comment]
FYI, about that x86_64-glibc failed build check, I just native-built the package on this arch and it turned out to be successful.

**Comment by atk** [comment]
The failure of the x64 build seems to stem from the process being killed after some time, not a failure with the build itself.

**Comment by loukamb** [comment]
I built this package myself as well and it built just fine. The automated builder just screws up, kills the process after an arbitrary delay and that avoids this package from being updated.

**Comment by atk** [comment]
I'm currently attempting to update this to 1.94.0, but they removed yarn in favor of using npm, which causes a lot of issues with the way we build things.

**Comment by atk** [comment]
There are still some issues, but I'm slowly getting there.

**Comment by Johnnynator** [comment]
Yes, I can do some Electron updates, kinda skipped too many of them.
Have a build job for it running right now, but I kinda expect that the build will be partially broken and will require some fixups for musl.

**Comment by atk** [comment]
This version also includes a fix for an RCE CVE: https://msrc.microsoft.com/update-guide/vulnerability/CVE-2024-43601, so I'd like to get it to the users asap.

**Comment by Johnnynator** [comment]
As expected, have the same problem as we have with chromium right now, the v8 jit is broken on musl, need to either get that fixed or find a way to get jitless wasm (drumbrake) working in electron (electron 32 uses a chromium version that is one major version too old to have drumbrake included :cry:  )

**Comment by atk** [comment]
electron v33 was just released. I guess we could go up one version without too much changes.

**Comment by atk** [comment]
@Johnnynator: do you have a working build for x64-glibc so I can already prepare whatever changes are required for the electron update?

**Comment by Johnnynator** [comment]
> @Johnnynator: do you have a working build for x64-glibc so I can already prepare whatever changes are required for the electron update?

Sorry, got a bit sidetracked and had some other things to do, some test builds are up: #52848 / https://void.johnnynator.dev/dev/electron33/

**Comment by atk** [comment]
It'll take a bit of time to test this. I'll push an intermediate step.

**Comment by atk** [comment]
@Johnnynator I get an error that `/usr/include/electron33/node_headers.tar.gz` is missing

**Comment by Johnnynator** [comment]
> @Johnnynator I get an error that `/usr/include/electron33/node_headers.tar.gz` is missing

Yep, electron did remove the option to ship this tarball. There are headers in electron33-devel. (Kinda like Alpine is doing it)

**Comment by atk** [comment]
That's strange, I added electron33-devel but still got the same message. Maybe it is in a different path? Have to investigate later.

**Comment by atk** [comment]
Got it up and running. Neither node-gyp nor graceful-fs are required anymore. Now all we need is for electron33 to be merged and then, this is ready for review after a rebase.

**Comment by atk** [comment]
Debugging this shows the error "cannot find module mkdirp", which is strange, since the module is clearly present in the build.

**Comment by atk** [comment]
We still have the same error and I cannot figure out why this happens. The library is there, it is just not loaded...

**Comment by Jipok** [comment]
Bump.
Seems new python extension version doesn't work with old(1.91.1) vscode. But old extension versions doesn't works with python 1.13.

**Comment by marmeladema** [comment]
Would https://vscodium.com be an easier alternative to package? It seems more in line with void-linux principles.

**Comment by loukamb** [comment]
VSCodium could be considered a fork of Code-OSS, and Void Linux has a strict policy against forks, so I'm unsure whether this would be accepted. It ultimately is up to contributor discretion.

**Comment by atk** [comment]
I had a look at vscodium and it does not have any patches that would address our current issue if we still want to build with a local electron from sources.

**Comment by oreo639** [comment]
> I had a look at vscodium and it does not have any patches that would address our current issue if we still want to build with a local electron from sources.

Yeah, I tried building it locally and a bunch of third party modules including but not limited to mkdirp are not present in `/usr/lib/code-oss/resources/app/node_modules`.
You can compare it with the archlinux package that includes them <https://archlinux.org/packages/extra/x86_64/code/>

**Comment by atk** [comment]
It seems there is already a fix within a later version of electron33, so I will try to build that, too.

**Comment by oreo639** [comment]
electron33 33.3.2 needs to be built with a specific chromium and npm release specified here: https://releases.electronjs.org/release/v33.3.2

I am currently building electron33 33.1.0 which is the first release including the patch, and the last electron33 series release that uses a non-extended stable verision of chromium. Extended stable versions of chromium don't have source tarballs available on the chromium-browser-official since they are primarily intended for commercial windows users.

Different distros handle that differently, looking at us, we just don't update to those versions, some Arch Linux uses git, OpenSUSE generates electron tarballs with chromium sources included (since electron does not provide official tarballs since their build system assumes a git environment), and FreeBSD hosts the chromium tarballs as github releases but has it split into multiple files due to upload limits. (most distros handle it by not shipping electron :p)

**Comment by oreo639** [comment]
Alright, I tested and can confirm that the crashing is resolved with electron33 33.1.0 although, as Johnnynator pointed out, I was mistaken as 3.2.0 is the last 33 series release using a non-extended stable chromium.

**Comment by atk** [comment]
OK, after updating electron, this should work.

**Comment by Johnnynator** [comment]
👍
