### PR TITLE
nvidia: update to 580.76.05

### PR DESCRIPTION
**Pull request by fvalasiad**
Another WIP incremental PR to test newer nvidia driver versions from Beta/New Feature branches until the next Production release.

Feel free to share issues!

edit: To avoid confusion, I'll include the branch which the PR is currently based on, since there is probably value in communicating with users about the instability risk of installing said drivers.

The TLDR is that in terms of reliability:
Production > New Feature > Beta.

### CODE REVIEW

**Comment by LZGM4702** [comment]
My nvidia-dkms 580.65.06 kept failing to build for the kernel. It think the make.log was something like tegra related.
Could be related to my computer though since I messed up my install a while back.

**Comment by fvalasiad** [comment]
Please share the make.log

**Comment by LZGM4702** [comment]
> Please share the make.log

Nvm i fixed it. It still fails when I reinstalled void but I am using linux-mainline 6.15.9

DKMS module 'nvidia-580.65.06' failed to build, please check /var/lib/dkms
for errors in the log file.

This is from make.log
nvidia/nv-clk.c:30:10: fatal error: soc/tegra/bpmp-abi.h: No such file or directory
   30 | #include <soc/tegra/bpmp-abi.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

Not fully sure what this means but it must not be detecting a tegra chip thing
so maybe you can remove that or something.

A patch like this should mitigate this issue,
"
+#if defined(NV_BPMP_ABI_H_PRESENT)
 #include <soc/tegra/bpmp-abi.h>
 #include <soc/tegra/bpmp.h>
+#endif

"

**Comment by fvalasiad** [comment]
Interesting, here is the context:

BPMP is short for **Boot and Power Management Processor** and it's a separate microcontroller in Tegra SoCs.

Tegra SoCs are a family of ARM-based chips for NVIDIA's line of embedded systems(e.g Jetson Nano, Xavier, Orin).

Essentially, they are irrelevant in the desktop, which is what we probably care about here, unless I am missing something.

It's interesting that it fails to build in mainline linux but not 6.12.41_1 I am currently in. I am suspecting that the file should not be built anyways, I'll investigate what's being built in my working version and report back.

**Comment by fvalasiad** [comment]
Never mind, I spent too much time digging sources in vain. Turns out your solution is correct, nvidia probably forgot to add a guard in those two headers. They have one everywhere else they include those two.

It's also unrelated to kernel version, I just missed it, thanks for pointing it out.

**Comment by LZGM4702** [comment]
> Never mind, I spent too much time digging sources in vain. Turns out your solution is correct, nvidia probably forgot to add a guard in those two headers. They have one everywhere else they include those two.
> 
> It's also unrelated to kernel version, I just missed it, thanks for pointing it out.

Ahh, well glad it turned out well in the end.

**Comment by fvalasiad** [comment]
@abenson Production release, feel free to merge.

**Comment by abenson** [comment]
~~Did you test it?~~ sorry, didn't see the patch. Does that break anything? Shouldn't since we don't do anything for ARMvidia

**Comment by fvalasiad** [comment]
> ~~Did you test it?~~ sorry, didn't see the patch. Does that break anything? Shouldn't since we don't do anything for ARMvidia

I've tested briefly, feel free to join! There are probably others who can share their experience with the update.

As far as the patch goes, even if we did anything with ARMvidia, I don't believe it'd be breaking anything. This header guard is used everywhere else they include those headers, and additionally while digging around I noticed they are checking for the presence of a bunch of headers, including these two, before they set the appropriate macro.

I kinda believe they simply forgot to add the guard, but that's just my guess.

**Comment by Datastreamx** [comment]
I installed this using this https://xbps-src-tutorials.github.io/pr-testing-tutorial.html as a guide. Thanks for your continued service fvalasiad!

I will be testing this further but first thing I noticed is that steam no longer starts. The logs seem to indicate gtk errors. I will be looking into it further to see if this is unrelated to the new driver. But it did only start showing up after install and reboot.

edit: I confirmed the new nvidia pkg is the issue because I just downgraded and steam works again. I couldn't really get anything useful out of the logging as it segfaults after installation verification without any logging other than "steam.sh: line 928: 19335 Segmentation fault      "$STEAMROOT/$STEAMEXEPATH" "$@""

Maybe it's the kernel I'm on being too old? I'm still on 6.12.41_1. 

Will try again in the weekend with some changes.

**Comment by fvalasiad** [comment]
> I installed this using this https://xbps-src-tutorials.github.io/pr-testing-tutorial.html as a guide. Thanks for your continued service fvalasiad!
> 
> I will be testing this further but first thing I noticed is that steam no longer starts. The logs seem to indicate gtk errors. I will be looking into it further to see if this is unrelated to the new driver. But it did only start showing up after install and reboot.
> 
> edit: I confirmed the new nvidia pkg is the issue because I just downgraded and steam works again. I couldn't really get anything useful out of the logging as it segfaults after installation verification without any logging other than "steam.sh: line 928: 19335 Segmentation fault "$STEAMROOT/$STEAMEXEPATH" "$@""
> 
> Maybe it's the kernel I'm on being too old? I'm still on 6.12.41_1.
> 
> Will try again in the weekend with some changes.

I've seen people report that GTK4 apps hang when closing a window with the new driver, does that match your experience?

**Comment by Datastreamx** [comment]
I didn't experience that issue with easyeffects and helvum. It must be something else. I see the branch has been merged so I'll have to dig into it some more later.

**Comment by fvalasiad** [comment]
> I didn't experience that issue with easyeffects and helvum. It must be something else. I see the branch has been merged so I'll have to dig into it some more later. 

I guess we can expect lots of bug reports if your experience isn't unique to your install, thanks for reporting anyways, and also for acknowledging my efforts!

**Comment by JkktBkkt** [comment]
> Never mind, I spent too much time digging sources in vain. Turns out your solution is correct, nvidia probably forgot to add a guard in those two headers. They have one everywhere else they include those two.
> 
> It's also unrelated to kernel version, I just missed it, thanks for pointing it out.

That seems to be the case, and if the open drivers are anything to go by, this was added in 575.51.02. 
Adapted the patch onto the open branch, quickly tested easyeffects, handbrake, d-spy (all gtk4-based), they all hanged on gui exit. Am going to roll back to 570.181 and not push the switch to 580 for now.
just in case, I'm on 6.12.41 currently and generally up-to-date otherwise

**Comment by cheinu-mike** [comment]
Sorry this might be irrelevant but I cannot get X server working on my machine with the 5060 ti in it claiming that this 580 driver version does not support this gpu. How is this possible? Nvidia claims this version should support the 5060 ti

**Comment by fvalasiad** [comment]
> Sorry this might be irrelevant but I cannot get X server working on my machine with the 5060 ti in it claiming that this 580 driver version does not support this gpu. How is this possible? Nvidia claims this version should support the 5060 ti
> 
> 
> 
> 

Consider #56685

Newer cards require the open kernel module, the default package uses the proprietary one, I've a PR open for the open package for the driver version 580.

Alternatively, if you wanna stick to an older version, consider @JkktBkkt 's PR. Note that they are different. Mine is all about installing it standalone to replace the system's nvidia package, the other replaces nvidia-dkms. So you need to install it alongside the nvidia package(version should match)

**Comment by ChrisW-B** [comment]
> I guess we can expect lots of bug reports if your experience isn't unique to your install, thanks for reporting anyways, and also for acknowledging my efforts!

Yeah, I'm getting flickering/corruption on Steam flatpak with both this update and your nvidia-open branch (verified that flatpak updated to org.freedesktop.Platform.GL.nvidia-580-76-05). 

(Kernel 6.12.41_1, nvidia 3070ti, niri desktop/xwayland-satellite for steam, let me know if there's anything helpful I can provide, though I'm guessing this is more related to wayland/xwayland than any driver issue. Easy enough to xdowngrade back to 570, so no big problems!)

Thanks again for your work on this!
