### ISSUE TITLE
Build RetroArch using OpenGL instead of OpenGLES

### ISSUE THREAD

**Issue by TegarOk** [void-linux/void-packages#32246]
### System

`Void 5.12.17_1 x86_64 AuthenticAMD notuptodate hold rrmFFFFF`
package:  `retroarch-1.9.7_1`

### Expected behavior
Should be build for OpenGL
### Actual behavior
Some cores didnt work because the repository build it for OpenGLES instead OpenGL, the cores is Citra for emulating Nintendo 3DS.
`[ERROR] Requesting OpenGL context, but RetroArch is compiled against OpenGLES. Cannot use HW context.`
### Steps to reproduce the behavior

- Install Retroarch from main repository.
- Running Retroarch and download the Citra cores, change value of HW Context to true from Core Options and finally select the games.
### Some Information
Download from https://buildbot.libretro.com/nightly/linux/x86_64/ and test it, 3DS get working.

**Comment by amak79** [comment]
`configure` is reporting that OpenGL is disabled.
```
Notice: OpenGL is disabled, Cg support will also be disabled.
Notice: OpenGL is disabled, OpenGL1 support will also be disabled.
```
I'm certain this wasn't the case before, so something must have changed. I will take a look.

**Comment by amak79** [comment]
> `configure` is reporting that OpenGL is disabled.
> 
> ```
> Notice: OpenGL is disabled, Cg support will also be disabled.
> Notice: OpenGL is disabled, OpenGL1 support will also be disabled.
> ```

This message is for OpenGL 2.0 so it shouldn't matter.

I can't reproduce this. I don't have any way to test the Citra core. I was able to test on x86_64 with the DuckStation core, which I believe is OpenGL only. The `GPU Render` core option is set to `Hardware (OpenGL)`. The RetroArch video driver is set to `glcore`.

What does `retroarch --features` report for OpenGL support?

Did you download the core manually or through RetroArch?

**Comment by amak79** [comment]
I can reproduce the error with the ParaLLEI N64 core, but get a segfault.

Some relevant info regarding `gl` and `glcore` drivers: https://www.libretro.com/index.php/changing-behavior-of-gl-and-glcore-video-drivers

I attempted to build with  OpenGL 2.0 (not sure if it's need) but that results in the following error.
```
LD retroarch
/usr/bin/ld: obj-unix/release/gfx/drivers/gl1.o: in function `draw_tex':
gl1.c:(.text+0xad9): undefined reference to `glMatrixMode'
/usr/bin/ld: gl1.c:(.text+0xade): undefined reference to `glPushMatrix'
/usr/bin/ld: gl1.c:(.text+0xae3): undefined reference to `glLoadIdentity'
/usr/bin/ld: gl1.c:(.text+0xaed): undefined reference to `glMatrixMode'
/usr/bin/ld: gl1.c:(.text+0xaf2): undefined reference to `glPushMatrix'
/usr/bin/ld: gl1.c:(.text+0xaf7): undefined reference to `glLoadIdentity'
/usr/bin/ld: gl1.c:(.text+0xb11): undefined reference to `glEnableClientState'
/usr/bin/ld: gl1.c:(.text+0xb1b): undefined reference to `glEnableClientState'
/usr/bin/ld: gl1.c:(.text+0xb25): undefined reference to `glEnableClientState'
/usr/bin/ld: gl1.c:(.text+0xb3b): undefined reference to `glColorPointer'
/usr/bin/ld: gl1.c:(.text+0xb51): undefined reference to `glVertexPointer'
/usr/bin/ld: gl1.c:(.text+0xb67): undefined reference to `glTexCoordPointer'
/usr/bin/ld: gl1.c:(.text+0xb82): undefined reference to `glDisableClientState'
/usr/bin/ld: gl1.c:(.text+0xb8c): undefined reference to `glDisableClientState'
/usr/bin/ld: gl1.c:(.text+0xb96): undefined reference to `glDisableClientState'
/usr/bin/ld: gl1.c:(.text+0xba0): undefined reference to `glMatrixMode'
/usr/bin/ld: gl1.c:(.text+0xba5): undefined reference to `glPopMatrix'
/usr/bin/ld: gl1.c:(.text+0xbaf): undefined reference to `glMatrixMode'
/usr/bin/ld: gl1.c:(.text+0xbb4): undefined reference to `glPopMatrix'
/usr/bin/ld: gl1.c:(.text+0xd25): undefined reference to `glRotatef'
/usr/bin/ld: obj-unix/release/gfx/drivers/gl1.o: in function `gl1_gfx_frame':
gl1.c:(.text+0x2864): undefined reference to `glMatrixMode'
/usr/bin/ld: gl1.c:(.text+0x2869): undefined reference to `glPushMatrix'
/usr/bin/ld: gl1.c:(.text+0x286e): undefined reference to `glLoadIdentity'
/usr/bin/ld: obj-unix/release/gfx/drivers_font/gl1_raster_font.o: in function `gl1_raster_font_draw_vertices':
gl1_raster_font.c:(.text+0x210): undefined reference to `glMatrixMode'
/usr/bin/ld: gl1_raster_font.c:(.text+0x215): undefined reference to `glPushMatrix'
/usr/bin/ld: gl1_raster_font.c:(.text+0x225): undefined reference to `glLoadMatrixf'
/usr/bin/ld: gl1_raster_font.c:(.text+0x22f): undefined reference to `glMatrixMode'
/usr/bin/ld: gl1_raster_font.c:(.text+0x234): undefined reference to `glPushMatrix'
/usr/bin/ld: gl1_raster_font.c:(.text+0x239): undefined reference to `glLoadIdentity'
/usr/bin/ld: gl1_raster_font.c:(.text+0x243): undefined reference to `glEnableClientState'
/usr/bin/ld: gl1_raster_font.c:(.text+0x24d): undefined reference to `glEnableClientState'
/usr/bin/ld: gl1_raster_font.c:(.text+0x257): undefined reference to `glEnableClientState'
/usr/bin/ld: gl1_raster_font.c:(.text+0x26b): undefined reference to `glVertexPointer'
/usr/bin/ld: gl1_raster_font.c:(.text+0x280): undefined reference to `glColorPointer'
/usr/bin/ld: gl1_raster_font.c:(.text+0x295): undefined reference to `glTexCoordPointer'
/usr/bin/ld: gl1_raster_font.c:(.text+0x2ae): undefined reference to `glDisableClientState'
/usr/bin/ld: gl1_raster_font.c:(.text+0x2b8): undefined reference to `glDisableClientState'
/usr/bin/ld: gl1_raster_font.c:(.text+0x2c2): undefined reference to `glDisableClientState'
/usr/bin/ld: gl1_raster_font.c:(.text+0x2cc): undefined reference to `glMatrixMode'
/usr/bin/ld: gl1_raster_font.c:(.text+0x2d1): undefined reference to `glPopMatrix'
/usr/bin/ld: gl1_raster_font.c:(.text+0x2db): undefined reference to `glMatrixMode'
/usr/bin/ld: gl1_raster_font.c:(.text+0x2e6): undefined reference to `glPopMatrix'
/usr/bin/ld: obj-unix/release/gfx/drivers_display/gfx_display_gl1.o: in function `gfx_display_gl1_draw':
gfx_display_gl1.c:(.text+0x194): undefined reference to `glMatrixMode'
/usr/bin/ld: gfx_display_gl1.c:(.text+0x199): undefined reference to `glPushMatrix'
/usr/bin/ld: gfx_display_gl1.c:(.text+0x1a1): undefined reference to `glLoadMatrixf'
/usr/bin/ld: gfx_display_gl1.c:(.text+0x1ab): undefined reference to `glMatrixMode'
/usr/bin/ld: gfx_display_gl1.c:(.text+0x1b0): undefined reference to `glPushMatrix'
/usr/bin/ld: gfx_display_gl1.c:(.text+0x1b5): undefined reference to `glLoadIdentity'
/usr/bin/ld: gfx_display_gl1.c:(.text+0x1bf): undefined reference to `glEnableClientState'
/usr/bin/ld: gfx_display_gl1.c:(.text+0x1c9): undefined reference to `glEnableClientState'
/usr/bin/ld: gfx_display_gl1.c:(.text+0x1d3): undefined reference to `glEnableClientState'
/usr/bin/ld: gfx_display_gl1.c:(.text+0x1eb): undefined reference to `glVertexPointer'
/usr/bin/ld: gfx_display_gl1.c:(.text+0x204): undefined reference to `glColorPointer'
/usr/bin/ld: gfx_display_gl1.c:(.text+0x21d): undefined reference to `glTexCoordPointer'
/usr/bin/ld: gfx_display_gl1.c:(.text+0x24e): undefined reference to `glDisableClientState'
/usr/bin/ld: gfx_display_gl1.c:(.text+0x258): undefined reference to `glDisableClientState'
/usr/bin/ld: gfx_display_gl1.c:(.text+0x262): undefined reference to `glDisableClientState'
/usr/bin/ld: gfx_display_gl1.c:(.text+0x26c): undefined reference to `glMatrixMode'
/usr/bin/ld: gfx_display_gl1.c:(.text+0x271): undefined reference to `glPopMatrix'
/usr/bin/ld: gfx_display_gl1.c:(.text+0x27b): undefined reference to `glMatrixMode'
/usr/bin/ld: gfx_display_gl1.c:(.text+0x280): undefined reference to `glPopMatrix'
collect2: error: ld returned 1 exit status
make: *** [Makefile:201: retroarch] Error 1
```

**Comment by amak79** [comment]
RetroArch isn't linking against `libGL.so.1` which explains why there is no OpenGL support, even though RetroArch claims it's enabled.

It appears that having both `opengl` and `gles2` isn't possible. I can run the ParaLLEI N64 core after disabling the `gles2` build option.

**Comment by TegarOk** [comment]
> What does `retroarch --features` report for OpenGL support?
https://pastebin.com/QbKypgAx
> Did you download the core manually or through RetroArch?
I download core through RetroArch. Should be same because i use the buildbot and its working.

**Comment by TegarOk** [comment]
> It appears that having both `opengl` and `gles2` isn't possible. I can run the ParaLLEI N64 core after disabling the `gles2` build option.

I have build & disable glse2 by typing "xbps-src -o ~glse2 pkg retroarch" but still same.

**Comment by amak79** [comment]
You may have a typo. It should be `gles2` not `glse2`. You can check with `xbps-query -S retroarch`.

**Comment by TegarOk** [comment]
Ah

> You may have a typo. It should be `gles2` not `glse2`. You can check with `xbps-query -S retroarch`.

No luck, im try gles2 too, but didnt work. Should i clear masterdir first?

**Comment by amak79** [comment]
Can you please post the output of `xbps-query -S retroarch`. That should tell us which options RetroArch was built with, and which repository it was installed from.

**Comment by TegarOk** [comment]
Ops i think the build is gles2.
I just remove masterdir and rebuild binary-bootstrap. But SHA256 is Error?

**Comment by amak79** [comment]
If you are having issues with building or installing a local package, you should ask for help in the #voidlinux IRC channel.

**Comment by TegarOk** [comment]
Maybe i will redownload the git. I think the git is corrupt because my internet.

**Comment by TegarOk** [comment]
For now, disable gles2 is the best solution.

**Comment by amak79** [comment]
@TegarOk can you please re-open this issue.

I think I've made some sense of the many of RetroArch OpenGL/ES configure options.
```
  --enable-opengl             Enable   OpenGL 2.0 support
  --disable-opengl            Disable  OpenGL 2.0 support
  --disable-opengl_core       Disable  Modern OpenGL driver support (GLES3+/GL3.2 core+), requires OpenGL.
  --disable-opengl1           Disable  OpenGL 1.1 support
  --enable-opengles           Enable   Use GLESv2 instead of desktop GL
  --enable-opengles3          Enable   OpenGLES3 support
  --enable-opengles3_1        Enable   OpenGLES3.1 support
  --enable-opengles3_2        Enable   OpenGLES3.2 support
```
The `--enable-opengl_core` option will enable both OpenGL (3.2+) and OpenGL ES (3+) support. I mistakenly thought that `--enable-opengles3` was needed for OpenGL ES support. I still don't know when this option should be used.

I've tested RetroArch with `opengl` enabled and `gles2` disabled on an RPi 3B+. RetroArch reports that OpenGL ES support is disabled and so far everything works.

I think I need to re-work the template to either disable `gles2` by default or drop it entirely.

@ericonr can you please add your thoughts on this issue.

**Comment by ericonr** [comment]
I don't know much about graphics APIs, sorry.

Wouldn't disabling gles2 break support for older rpis? Say the 1 or 2?

**Comment by amak79** [comment]
> Wouldn't disabling gles2 break support for older rpis? Say the 1 or 2?

I don't think it will since all Pi's can only do OpenGL ES. Disabling `gles2` worked on my 3B+, but I will also test it on my Zero.

**Comment by amak79** [comment]
I'm able to run RetroArch on a Pi Zero with `gles2` disabled, although I can't test any cores since there are no pre-compiled cores for `armv6l`.

**Comment by amak79** [comment]
To summarise my findings:

The `--enable-opengl_core` option (`opengl` build option) will build RetroAch with OpenGL 3.2+ and OpenGL ES 3+ support. The `--enable-opengles` and `--enable-opengles3` options (`gles2` build option) will build RetroAch with **only** OpenGL ES 2/3 support. Currently the RetroArch package is built with only OpenGL ES support, which breaks OpenGL only cores. It also means that OpenGL capable machines are using OpenGL ES instead.

I propose that `gles2` be disabled by default. The `opengl` option be renamed to `glcore`, and a description added to better reflect what it actually does.

Since my knowledge of graphics APIs is limited, can any Void dev with graphics API knowledge please take a look at this issue and provide some feedback.

**Comment by ericonr** [comment]
That sounds reasonable to me.

Ping @q66 and @st3r4g, I suppose.

**Comment by st3r4g** [comment]
https://github.com/libretro/RetroArch/blob/bdba803909bd8d703ee8b6b784647f68f4e8e486/qb/config.params.sh#L88

Indeed `HAVE_OPENGLES` excludes desktop GL. So it has to be disabled.

I don't know anything about RPi graphics, but they use the `vc4` driver, which is a GLES2 driver so I guess it doesn't implement pure GLES3 functions...
